-- V2 retail transaction and customer analytics schema (PostgreSQL 15+ / 18 tested target)
-- Additive by design: legacy public tables are never dropped.
BEGIN;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE SCHEMA IF NOT EXISTS auth;
CREATE SCHEMA IF NOT EXISTS biz;
CREATE SCHEMA IF NOT EXISTS ods;
CREATE SCHEMA IF NOT EXISTS dwd;
CREATE SCHEMA IF NOT EXISTS ads;
CREATE SCHEMA IF NOT EXISTS ml;
CREATE SCHEMA IF NOT EXISTS audit;

CREATE TABLE IF NOT EXISTS auth.account (
    account_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username        VARCHAR(64) NOT NULL UNIQUE,
    password_hash   VARCHAR(255) NOT NULL,
    full_name       VARCHAR(128) NOT NULL DEFAULT '',
    role            VARCHAR(20) NOT NULL DEFAULT 'analyst'
                    CHECK (role IN ('admin', 'operator', 'analyst')),
    is_active       BOOLEAN NOT NULL DEFAULT TRUE,
    last_login_at   TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS biz.customer (
    customer_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_no     VARCHAR(32) NOT NULL UNIQUE,
    name            VARCHAR(128) NOT NULL,
    gender          VARCHAR(16),
    phone           VARCHAR(32),
    email           VARCHAR(128),
    province        VARCHAR(64),
    city            VARCHAR(64),
    registered_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    status          VARCHAR(16) NOT NULL DEFAULT 'active'
                    CHECK (status IN ('active', 'inactive', 'blocked')),
    legacy_user_id  BIGINT UNIQUE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS biz.product_category (
    category_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name   VARCHAR(80) NOT NULL UNIQUE,
    parent_id       BIGINT REFERENCES biz.product_category(category_id),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS biz.product (
    product_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku             VARCHAR(64) NOT NULL UNIQUE,
    product_name    VARCHAR(160) NOT NULL,
    category_id     BIGINT REFERENCES biz.product_category(category_id),
    unit_price      NUMERIC(14,2) NOT NULL CHECK (unit_price >= 0),
    stock_qty       INTEGER NOT NULL DEFAULT 0 CHECK (stock_qty >= 0),
    status          VARCHAR(16) NOT NULL DEFAULT 'active'
                    CHECK (status IN ('active', 'inactive')),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS biz.sales_order (
    order_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_no        VARCHAR(40) NOT NULL UNIQUE,
    customer_id     BIGINT NOT NULL REFERENCES biz.customer(customer_id),
    status          VARCHAR(24) NOT NULL DEFAULT 'awaiting_payment'
                    CHECK (status IN ('awaiting_payment', 'paid', 'partially_refunded', 'refunded', 'cancelled')),
    total_amount    NUMERIC(14,2) NOT NULL CHECK (total_amount >= 0),
    paid_amount     NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (paid_amount >= 0),
    refunded_amount NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (refunded_amount >= 0),
    ordered_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    paid_at         TIMESTAMPTZ,
    remark          VARCHAR(255),
    created_by      BIGINT REFERENCES auth.account(account_id),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK (paid_amount <= total_amount),
    CHECK (refunded_amount <= paid_amount)
);

CREATE TABLE IF NOT EXISTS biz.order_item (
    order_item_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id        BIGINT NOT NULL REFERENCES biz.sales_order(order_id) ON DELETE CASCADE,
    product_id      BIGINT NOT NULL REFERENCES biz.product(product_id),
    quantity        INTEGER NOT NULL CHECK (quantity > 0),
    unit_price      NUMERIC(14,2) NOT NULL CHECK (unit_price >= 0),
    line_amount     NUMERIC(14,2) NOT NULL CHECK (line_amount = round(unit_price * quantity, 2)),
    UNIQUE (order_id, product_id)
);

CREATE TABLE IF NOT EXISTS biz.payment (
    payment_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_no      VARCHAR(40) NOT NULL UNIQUE,
    order_id        BIGINT NOT NULL REFERENCES biz.sales_order(order_id),
    method          VARCHAR(24) NOT NULL CHECK (method IN ('wechat', 'alipay', 'bank_card', 'cash')),
    amount          NUMERIC(14,2) NOT NULL CHECK (amount > 0),
    status          VARCHAR(16) NOT NULL DEFAULT 'success'
                    CHECK (status IN ('pending', 'success', 'failed')),
    paid_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    transaction_ref VARCHAR(96),
    created_by      BIGINT REFERENCES auth.account(account_id),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_success_payment_order
    ON biz.payment(order_id) WHERE status = 'success';

CREATE TABLE IF NOT EXISTS biz.refund (
    refund_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    refund_no       VARCHAR(40) NOT NULL UNIQUE,
    payment_id      BIGINT NOT NULL REFERENCES biz.payment(payment_id),
    order_id        BIGINT NOT NULL REFERENCES biz.sales_order(order_id),
    amount          NUMERIC(14,2) NOT NULL CHECK (amount > 0),
    reason          VARCHAR(255) NOT NULL,
    status          VARCHAR(16) NOT NULL DEFAULT 'success'
                    CHECK (status IN ('pending', 'success', 'failed')),
    refunded_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by      BIGINT REFERENCES auth.account(account_id),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS ods.legacy_spending (
    source_key      VARCHAR(80) PRIMARY KEY,
    raw_data        JSONB NOT NULL,
    imported_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    processed       BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS ods.import_batch (
    batch_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_no          VARCHAR(64) NOT NULL UNIQUE,
    source_name       VARCHAR(128) NOT NULL,
    status            VARCHAR(16) NOT NULL DEFAULT 'running'
                      CHECK (status IN ('running', 'success', 'failed')),
    customer_count    INTEGER NOT NULL DEFAULT 0,
    transaction_count INTEGER NOT NULL DEFAULT 0,
    started_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    finished_at       TIMESTAMPTZ,
    error_message     TEXT,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS dwd.consumption_flow (
    flow_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id     BIGINT NOT NULL REFERENCES biz.customer(customer_id),
    order_id        BIGINT NOT NULL REFERENCES biz.sales_order(order_id),
    payment_id      BIGINT REFERENCES biz.payment(payment_id),
    refund_id       BIGINT REFERENCES biz.refund(refund_id),
    flow_type       VARCHAR(16) NOT NULL CHECK (flow_type IN ('payment', 'refund')),
    gross_amount    NUMERIC(14,2) NOT NULL CHECK (gross_amount >= 0),
    net_amount      NUMERIC(14,2) NOT NULL,
    occurred_at     TIMESTAMPTZ NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK ((flow_type = 'payment' AND net_amount > 0) OR (flow_type = 'refund' AND net_amount < 0))
);

CREATE TABLE IF NOT EXISTS ads.customer_rfm (
    customer_id     BIGINT PRIMARY KEY REFERENCES biz.customer(customer_id),
    recency_days    INTEGER NOT NULL,
    frequency       INTEGER NOT NULL,
    monetary        NUMERIC(16,2) NOT NULL,
    r_score         SMALLINT NOT NULL CHECK (r_score BETWEEN 1 AND 5),
    f_score         SMALLINT NOT NULL CHECK (f_score BETWEEN 1 AND 5),
    m_score         SMALLINT NOT NULL CHECK (m_score BETWEEN 1 AND 5),
    segment         VARCHAR(40) NOT NULL,
    task_id         BIGINT,
    calculated_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS ml.model_task (
    task_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_type       VARCHAR(24) NOT NULL CHECK (task_type IN ('rfm', 'kmeans', 'churn')),
    status          VARCHAR(16) NOT NULL DEFAULT 'running'
                    CHECK (status IN ('running', 'success', 'failed')),
    parameters      JSONB NOT NULL DEFAULT '{}'::jsonb,
    started_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    finished_at     TIMESTAMPTZ,
    error_message   TEXT,
    created_by      BIGINT REFERENCES auth.account(account_id)
);

ALTER TABLE ads.customer_rfm
    DROP CONSTRAINT IF EXISTS customer_rfm_task_id_fkey;
ALTER TABLE ads.customer_rfm
    ADD CONSTRAINT customer_rfm_task_id_fkey FOREIGN KEY (task_id) REFERENCES ml.model_task(task_id);

CREATE TABLE IF NOT EXISTS ml.model_metric (
    metric_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id         BIGINT NOT NULL REFERENCES ml.model_task(task_id) ON DELETE CASCADE,
    metric_name     VARCHAR(40) NOT NULL,
    metric_value    NUMERIC(18,6) NOT NULL,
    dataset         VARCHAR(16) NOT NULL DEFAULT 'all',
    UNIQUE (task_id, metric_name, dataset)
);

CREATE TABLE IF NOT EXISTS ml.rfm_result (
    task_id         BIGINT NOT NULL REFERENCES ml.model_task(task_id) ON DELETE CASCADE,
    customer_id     BIGINT NOT NULL REFERENCES biz.customer(customer_id),
    recency_days    INTEGER NOT NULL,
    frequency       INTEGER NOT NULL,
    monetary        NUMERIC(16,2) NOT NULL,
    r_score         SMALLINT NOT NULL,
    f_score         SMALLINT NOT NULL,
    m_score         SMALLINT NOT NULL,
    segment         VARCHAR(40) NOT NULL,
    PRIMARY KEY (task_id, customer_id)
);

CREATE TABLE IF NOT EXISTS ml.cluster_result (
    task_id         BIGINT NOT NULL REFERENCES ml.model_task(task_id) ON DELETE CASCADE,
    customer_id     BIGINT NOT NULL REFERENCES biz.customer(customer_id),
    cluster_label   INTEGER NOT NULL,
    distance        NUMERIC(18,6),
    PRIMARY KEY (task_id, customer_id)
);

CREATE TABLE IF NOT EXISTS ml.churn_prediction (
    task_id         BIGINT NOT NULL REFERENCES ml.model_task(task_id) ON DELETE CASCADE,
    customer_id     BIGINT NOT NULL REFERENCES biz.customer(customer_id),
    churn_probability NUMERIC(8,6) NOT NULL CHECK (churn_probability BETWEEN 0 AND 1),
    predicted_label BOOLEAN NOT NULL,
    PRIMARY KEY (task_id, customer_id)
);

CREATE TABLE IF NOT EXISTS audit.login_log (
    login_log_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id      BIGINT REFERENCES auth.account(account_id),
    username        VARCHAR(64),
    status          VARCHAR(16) NOT NULL CHECK (status IN ('success', 'failed')),
    fail_reason     VARCHAR(64),
    ip_address      INET,
    user_agent      VARCHAR(255),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS audit.operation_log (
    operation_log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operator_id     BIGINT REFERENCES auth.account(account_id),
    action          VARCHAR(64) NOT NULL,
    entity_type     VARCHAR(40),
    entity_id       VARCHAR(64),
    details         JSONB NOT NULL DEFAULT '{}'::jsonb,
    ip_address      INET,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_customer_name ON biz.customer(name);
CREATE INDEX IF NOT EXISTS idx_product_category ON biz.product(category_id);
CREATE INDEX IF NOT EXISTS idx_order_customer_time ON biz.sales_order(customer_id, ordered_at DESC);
CREATE INDEX IF NOT EXISTS idx_order_status_time ON biz.sales_order(status, ordered_at DESC);
CREATE INDEX IF NOT EXISTS idx_payment_order ON biz.payment(order_id);
CREATE INDEX IF NOT EXISTS idx_refund_order ON biz.refund(order_id);
CREATE INDEX IF NOT EXISTS idx_flow_customer_time ON dwd.consumption_flow(customer_id, occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_flow_order ON dwd.consumption_flow(order_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_payment_consumption_flow
    ON dwd.consumption_flow(payment_id) WHERE flow_type = 'payment';
CREATE UNIQUE INDEX IF NOT EXISTS uq_refund_consumption_flow
    ON dwd.consumption_flow(refund_id) WHERE flow_type = 'refund';
CREATE INDEX IF NOT EXISTS idx_import_batch_time ON ods.import_batch(started_at DESC);
CREATE INDEX IF NOT EXISTS idx_task_type_time ON ml.model_task(task_type, started_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_operator_time ON audit.operation_log(operator_id, created_at DESC);

CREATE OR REPLACE VIEW ads.customer_value_summary AS
SELECT c.customer_id, c.customer_no, c.name,
       COUNT(DISTINCT o.order_id) FILTER (WHERE o.status <> 'cancelled') AS order_count,
       COALESCE(SUM(f.net_amount), 0)::NUMERIC(16,2) AS net_amount,
       MAX(f.occurred_at) FILTER (WHERE f.flow_type = 'payment') AS last_purchase_at
FROM biz.customer c
LEFT JOIN biz.sales_order o ON o.customer_id = c.customer_id
LEFT JOIN dwd.consumption_flow f ON f.order_id = o.order_id
GROUP BY c.customer_id, c.customer_no, c.name;

COMMIT;
