CREATE TABLE IF NOT EXISTS auth.role (
    role_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_code       VARCHAR(64) NOT NULL UNIQUE,
    role_name       VARCHAR(100) NOT NULL,
    description     VARCHAR(255) NOT NULL DEFAULT '',
    is_active       BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS auth.permission (
    permission_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    permission_code VARCHAR(100) NOT NULL UNIQUE,
    permission_name VARCHAR(120) NOT NULL,
    resource_type   VARCHAR(40) NOT NULL,
    is_active       BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS auth.account_role (
    account_id      BIGINT NOT NULL REFERENCES auth.account(account_id) ON DELETE CASCADE,
    role_id         BIGINT NOT NULL REFERENCES auth.role(role_id) ON DELETE CASCADE,
    is_primary      BOOLEAN NOT NULL DEFAULT FALSE,
    assigned_by     BIGINT REFERENCES auth.account(account_id),
    assigned_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (account_id, role_id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_account_primary_role
    ON auth.account_role(account_id) WHERE is_primary;

CREATE TABLE IF NOT EXISTS auth.role_permission (
    role_id         BIGINT NOT NULL REFERENCES auth.role(role_id) ON DELETE CASCADE,
    permission_id   BIGINT NOT NULL REFERENCES auth.permission(permission_id) ON DELETE CASCADE,
    granted_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (role_id, permission_id)
);

CREATE TABLE IF NOT EXISTS audit.data_change_log (
    change_log_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id      BIGINT REFERENCES auth.account(account_id),
    action          VARCHAR(32) NOT NULL,
    schema_name     VARCHAR(64) NOT NULL,
    table_name      VARCHAR(64) NOT NULL,
    record_id       VARCHAR(128),
    before_data     JSONB,
    after_data      JSONB,
    ip_address      INET,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS audit.import_log (
    import_log_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id      BIGINT REFERENCES auth.account(account_id),
    source_name     VARCHAR(255) NOT NULL,
    status          VARCHAR(16) NOT NULL CHECK (status IN ('running', 'success', 'failed')),
    accepted_rows   INTEGER NOT NULL DEFAULT 0 CHECK (accepted_rows >= 0),
    rejected_rows   INTEGER NOT NULL DEFAULT 0 CHECK (rejected_rows >= 0),
    error_message   TEXT,
    started_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    finished_at     TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS audit.interface_log (
    interface_log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id       BIGINT REFERENCES auth.account(account_id),
    api_name         VARCHAR(100) NOT NULL,
    request_path     VARCHAR(255) NOT NULL,
    status_code      INTEGER NOT NULL,
    elapsed_ms       INTEGER NOT NULL DEFAULT 0 CHECK (elapsed_ms >= 0),
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_account_role_account ON auth.account_role(account_id);
CREATE INDEX IF NOT EXISTS idx_role_permission_role ON auth.role_permission(role_id);
CREATE INDEX IF NOT EXISTS idx_change_log_record ON audit.data_change_log(schema_name, table_name, record_id);
CREATE INDEX IF NOT EXISTS idx_interface_log_time ON audit.interface_log(created_at DESC);

INSERT INTO auth.role (role_code, role_name, description) VALUES
('super_admin', '超级管理员', '系统最高权限与全局配置'),
('system_admin', '系统管理员', '账号、权限和审计管理'),
('customer_operator', '客户运营人员', '客户档案与客户运营'),
('product_operator', '商品库存人员', '商品、分类与库存维护'),
('order_operator', '订单业务人员', '订单、支付与退款申请'),
('finance_auditor', '财务审核人员', '支付核对与退款审核'),
('data_analyst', '数据分析人员', '经营分析与报表导出'),
('model_operator', '算法建模人员', '模型任务与预测结果'),
('knowledge_admin', '知识库管理员', '知识文档与发布管理'),
('qa_operator', '智能客服人员', '问答反馈与人工工单')
ON CONFLICT (role_code) DO UPDATE SET
    role_name = EXCLUDED.role_name,
    description = EXCLUDED.description,
    is_active = TRUE,
    updated_at = now();

INSERT INTO auth.permission (permission_code, permission_name, resource_type) VALUES
('system.manage', '系统与账号管理', 'system'),
('audit.read', '查看审计日志', 'audit'),
('customer.read', '查看客户', 'customer'),
('customer.write', '维护客户', 'customer'),
('product.read', '查看商品', 'product'),
('product.write', '维护商品', 'product'),
('inventory.read', '查看库存', 'inventory'),
('inventory.write', '调整库存', 'inventory'),
('order.read', '查看订单', 'order'),
('order.write', '维护订单', 'order'),
('payment.read', '查看支付', 'payment'),
('payment.write', '发起支付', 'payment'),
('refund.read', '查看退款', 'refund'),
('refund.request', '发起退款', 'refund'),
('refund.approve', '审核退款', 'refund'),
('analysis.read', '查看经营分析', 'analysis'),
('analysis.run', '执行经营分析', 'analysis'),
('analysis.export', '导出经营报表', 'analysis'),
('model.read', '查看模型任务', 'model'),
('model.run', '执行模型任务', 'model'),
('knowledge.read', '查看知识库', 'knowledge'),
('knowledge.write', '维护知识库', 'knowledge'),
('knowledge.publish', '发布知识文档', 'knowledge'),
('qa.read', '查看问答记录', 'qa'),
('qa.handle', '处理人工工单', 'qa'),
('import.read', '查看导入批次', 'import'),
('import.run', '执行数据导入', 'import'),
('sql.execute', '执行只读SQL', 'sql')
ON CONFLICT (permission_code) DO UPDATE SET
    permission_name = EXCLUDED.permission_name,
    resource_type = EXCLUDED.resource_type,
    is_active = TRUE;

INSERT INTO auth.role_permission (role_id, permission_id)
SELECT r.role_id, p.permission_id
FROM auth.role r CROSS JOIN auth.permission p
WHERE r.role_code = 'super_admin'
ON CONFLICT DO NOTHING;

WITH grants(role_code, permission_code) AS (VALUES
    ('system_admin', 'system.manage'), ('system_admin', 'audit.read'),
    ('system_admin', 'customer.read'), ('system_admin', 'product.read'),
    ('system_admin', 'order.read'), ('system_admin', 'payment.read'),
    ('system_admin', 'refund.read'), ('system_admin', 'analysis.read'),
    ('customer_operator', 'customer.read'), ('customer_operator', 'customer.write'),
    ('customer_operator', 'analysis.read'),
    ('product_operator', 'product.read'), ('product_operator', 'product.write'),
    ('product_operator', 'inventory.read'), ('product_operator', 'inventory.write'),
    ('product_operator', 'order.read'),
    ('order_operator', 'customer.read'), ('order_operator', 'product.read'),
    ('order_operator', 'inventory.read'), ('order_operator', 'order.read'),
    ('order_operator', 'order.write'), ('order_operator', 'payment.read'),
    ('order_operator', 'payment.write'), ('order_operator', 'refund.read'),
    ('order_operator', 'refund.request'),
    ('finance_auditor', 'payment.read'), ('finance_auditor', 'refund.read'),
    ('finance_auditor', 'refund.approve'), ('finance_auditor', 'audit.read'),
    ('finance_auditor', 'analysis.read'),
    ('data_analyst', 'customer.read'), ('data_analyst', 'product.read'),
    ('data_analyst', 'order.read'), ('data_analyst', 'payment.read'),
    ('data_analyst', 'refund.read'), ('data_analyst', 'analysis.read'),
    ('data_analyst', 'analysis.run'), ('data_analyst', 'analysis.export'),
    ('data_analyst', 'model.read'),
    ('model_operator', 'customer.read'), ('model_operator', 'product.read'),
    ('model_operator', 'analysis.read'), ('model_operator', 'model.read'),
    ('model_operator', 'model.run'),
    ('knowledge_admin', 'knowledge.read'), ('knowledge_admin', 'knowledge.write'),
    ('knowledge_admin', 'knowledge.publish'), ('knowledge_admin', 'qa.read'),
    ('qa_operator', 'knowledge.read'), ('qa_operator', 'qa.read'),
    ('qa_operator', 'qa.handle'), ('qa_operator', 'customer.read'),
    ('qa_operator', 'order.read'), ('qa_operator', 'payment.read'),
    ('qa_operator', 'refund.read')
)
INSERT INTO auth.role_permission (role_id, permission_id)
SELECT r.role_id, p.permission_id
FROM grants g
JOIN auth.role r ON r.role_code = g.role_code
JOIN auth.permission p ON p.permission_code = g.permission_code
ON CONFLICT DO NOTHING;

WITH assignments(username, role_code, is_primary) AS (VALUES
    ('admin', 'super_admin', TRUE),
    ('operator', 'order_operator', TRUE),
    ('operator', 'customer_operator', FALSE),
    ('operator', 'product_operator', FALSE),
    ('analyst', 'data_analyst', TRUE),
    ('analyst', 'model_operator', FALSE)
)
INSERT INTO auth.account_role (account_id, role_id, is_primary)
SELECT a.account_id, r.role_id, x.is_primary
FROM assignments x
JOIN auth.account a ON a.username = x.username
JOIN auth.role r ON r.role_code = x.role_code
ON CONFLICT (account_id, role_id) DO UPDATE SET is_primary = EXCLUDED.is_primary;
