ALTER TABLE biz.refund
    DROP CONSTRAINT IF EXISTS refund_status_check;

ALTER TABLE biz.refund
    ALTER COLUMN status SET DEFAULT 'pending',
    ALTER COLUMN refunded_at DROP NOT NULL,
    ADD COLUMN IF NOT EXISTS requested_by BIGINT REFERENCES auth.account(account_id),
    ADD COLUMN IF NOT EXISTS reviewed_by BIGINT REFERENCES auth.account(account_id),
    ADD COLUMN IF NOT EXISTS reviewed_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS review_note VARCHAR(255);

ALTER TABLE biz.refund
    ADD CONSTRAINT refund_status_check
    CHECK (status IN ('pending', 'approved', 'rejected', 'success', 'failed'));

UPDATE biz.refund
SET requested_by = COALESCE(requested_by, created_by),
    reviewed_by = COALESCE(reviewed_by, created_by),
    reviewed_at = COALESCE(reviewed_at, refunded_at),
    review_note = COALESCE(review_note, '历史退款迁移')
WHERE status = 'success';

CREATE TABLE IF NOT EXISTS biz.refund_item (
    refund_item_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    refund_id       BIGINT NOT NULL REFERENCES biz.refund(refund_id) ON DELETE CASCADE,
    order_item_id   BIGINT NOT NULL REFERENCES biz.order_item(order_item_id),
    quantity        INTEGER NOT NULL CHECK (quantity > 0),
    refund_amount   NUMERIC(14,2) NOT NULL CHECK (refund_amount > 0),
    returned_qty    INTEGER NOT NULL DEFAULT 0 CHECK (returned_qty BETWEEN 0 AND quantity),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (refund_id, order_item_id)
);

INSERT INTO biz.refund_item
    (refund_id, order_item_id, quantity, refund_amount, returned_qty)
SELECT r.refund_id, item.order_item_id, 1, r.amount, 0
FROM biz.refund r
JOIN LATERAL (
    SELECT oi.order_item_id
    FROM biz.order_item oi
    WHERE oi.order_id = r.order_id
    ORDER BY oi.order_item_id
    LIMIT 1
) item ON TRUE
WHERE NOT EXISTS (
    SELECT 1 FROM biz.refund_item ri WHERE ri.refund_id = r.refund_id
);

CREATE TABLE IF NOT EXISTS biz.inventory_log (
    inventory_log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id       BIGINT NOT NULL REFERENCES biz.product(product_id),
    order_id         BIGINT REFERENCES biz.sales_order(order_id),
    refund_id        BIGINT REFERENCES biz.refund(refund_id),
    refund_item_id   BIGINT UNIQUE REFERENCES biz.refund_item(refund_item_id),
    change_type      VARCHAR(24) NOT NULL
                     CHECK (change_type IN ('sale', 'refund_return', 'cancel_return', 'manual_adjustment')),
    quantity_delta   INTEGER NOT NULL CHECK (quantity_delta <> 0),
    before_qty       INTEGER NOT NULL CHECK (before_qty >= 0),
    after_qty        INTEGER NOT NULL CHECK (after_qty >= 0),
    operator_id      BIGINT REFERENCES auth.account(account_id),
    remark           VARCHAR(255),
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK (after_qty = before_qty + quantity_delta)
);

CREATE INDEX IF NOT EXISTS idx_refund_status_time
    ON biz.refund(status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_refund_item_order_item
    ON biz.refund_item(order_item_id);
CREATE INDEX IF NOT EXISTS idx_inventory_product_time
    ON biz.inventory_log(product_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_inventory_order
    ON biz.inventory_log(order_id);
