CREATE SCHEMA IF NOT EXISTS kb;

CREATE TABLE kb.knowledge_base (
    knowledge_base_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    base_code         VARCHAR(64) NOT NULL UNIQUE,
    name              VARCHAR(160) NOT NULL,
    description       VARCHAR(500) NOT NULL DEFAULT '',
    status            VARCHAR(16) NOT NULL DEFAULT 'active'
                      CHECK (status IN ('active', 'disabled')),
    created_by        BIGINT REFERENCES auth.account(account_id),
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE kb.document (
    document_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    knowledge_base_id BIGINT NOT NULL REFERENCES kb.knowledge_base(knowledge_base_id),
    title             VARCHAR(200) NOT NULL,
    version           INTEGER NOT NULL DEFAULT 1 CHECK (version > 0),
    original_name     VARCHAR(255) NOT NULL,
    storage_name      VARCHAR(100) NOT NULL UNIQUE,
    extension         VARCHAR(12) NOT NULL,
    mime_type         VARCHAR(120) NOT NULL DEFAULT 'application/octet-stream',
    file_size         BIGINT NOT NULL CHECK (file_size > 0),
    content_hash      CHAR(64) NOT NULL,
    status            VARCHAR(20) NOT NULL DEFAULT 'processing'
                      CHECK (status IN ('processing', 'ready', 'failed', 'disabled')),
    is_published      BOOLEAN NOT NULL DEFAULT FALSE,
    chunk_count       INTEGER NOT NULL DEFAULT 0 CHECK (chunk_count >= 0),
    error_message     TEXT,
    created_by        BIGINT REFERENCES auth.account(account_id),
    published_by      BIGINT REFERENCES auth.account(account_id),
    published_at      TIMESTAMPTZ,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (knowledge_base_id, title, version),
    CHECK (NOT is_published OR (status = 'ready' AND published_at IS NOT NULL))
);

CREATE TABLE kb.document_chunk (
    chunk_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id       BIGINT NOT NULL REFERENCES kb.document(document_id) ON DELETE CASCADE,
    chunk_no          INTEGER NOT NULL CHECK (chunk_no > 0),
    content           TEXT NOT NULL CHECK (length(btrim(content)) > 0),
    char_count        INTEGER NOT NULL CHECK (char_count > 0),
    content_hash      CHAR(64) NOT NULL,
    search_terms      TEXT[] NOT NULL,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (document_id, chunk_no),
    CHECK (cardinality(search_terms) > 0)
);

CREATE INDEX idx_kb_document_base_status
    ON kb.document(knowledge_base_id, status, is_published, updated_at DESC);
CREATE INDEX idx_kb_chunk_document ON kb.document_chunk(document_id, chunk_no);
CREATE INDEX idx_kb_chunk_search_terms ON kb.document_chunk USING GIN(search_terms);
