CREATE SCHEMA IF NOT EXISTS qa;

CREATE TABLE qa.qa_session (
    session_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id        BIGINT REFERENCES auth.account(account_id),
    title             VARCHAR(200) NOT NULL DEFAULT '新会话',
    status            VARCHAR(16) NOT NULL DEFAULT 'active'
                      CHECK (status IN ('active', 'closed')),
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE qa.qa_message (
    message_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id        BIGINT NOT NULL REFERENCES qa.qa_session(session_id) ON DELETE CASCADE,
    account_id        BIGINT REFERENCES auth.account(account_id),
    message_role      VARCHAR(16) NOT NULL CHECK (message_role IN ('user', 'assistant', 'system')),
    message_status    VARCHAR(16) NOT NULL DEFAULT 'success'
                      CHECK (message_status IN ('success', 'refusal', 'error')),
    content           TEXT NOT NULL CHECK (length(btrim(content)) > 0),
    confidence        NUMERIC(6,5) CHECK (confidence BETWEEN 0 AND 1),
    provider_model    VARCHAR(120),
    prompt_version    VARCHAR(40),
    latency_ms        INTEGER CHECK (latency_ms >= 0),
    prompt_tokens     INTEGER CHECK (prompt_tokens >= 0),
    completion_tokens INTEGER CHECK (completion_tokens >= 0),
    error_code        VARCHAR(80),
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE qa.qa_retrieval_log (
    retrieval_log_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id        BIGINT NOT NULL REFERENCES qa.qa_message(message_id) ON DELETE CASCADE,
    chunk_id          BIGINT NOT NULL REFERENCES kb.document_chunk(chunk_id),
    rank              INTEGER NOT NULL CHECK (rank > 0),
    distance          DOUBLE PRECISION NOT NULL CHECK (distance >= 0),
    excerpt           TEXT NOT NULL,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (message_id, rank),
    UNIQUE (message_id, chunk_id)
);

CREATE TABLE qa.qa_feedback (
    feedback_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id        BIGINT NOT NULL REFERENCES qa.qa_message(message_id) ON DELETE CASCADE,
    account_id        BIGINT NOT NULL REFERENCES auth.account(account_id),
    is_helpful        BOOLEAN NOT NULL,
    comment           VARCHAR(500) NOT NULL DEFAULT '',
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (message_id, account_id)
);

CREATE TABLE qa.qa_ticket (
    ticket_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id        BIGINT NOT NULL REFERENCES qa.qa_session(session_id),
    source_message_id BIGINT NOT NULL REFERENCES qa.qa_message(message_id),
    fallback_message_id BIGINT REFERENCES qa.qa_message(message_id),
    status            VARCHAR(16) NOT NULL DEFAULT 'pending'
                      CHECK (status IN ('pending', 'assigned', 'resolved', 'closed')),
    priority          VARCHAR(12) NOT NULL DEFAULT 'normal'
                      CHECK (priority IN ('low', 'normal', 'high')),
    reason_code       VARCHAR(80) NOT NULL,
    assigned_to       BIGINT REFERENCES auth.account(account_id),
    response_text     TEXT,
    resolution_note   VARCHAR(1000),
    assigned_at       TIMESTAMPTZ,
    resolved_at       TIMESTAMPTZ,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (source_message_id)
);

CREATE INDEX idx_qa_session_account_time ON qa.qa_session(account_id, updated_at DESC);
CREATE INDEX idx_qa_message_session_time ON qa.qa_message(session_id, created_at, message_id);
CREATE INDEX idx_qa_ticket_status_time ON qa.qa_ticket(status, created_at);
CREATE INDEX idx_qa_ticket_assignee ON qa.qa_ticket(assigned_to, status);

