CREATE TABLE IF NOT EXISTS audit.background_job (
    job_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_type        VARCHAR(64) NOT NULL,
    payload         JSONB NOT NULL DEFAULT '{}'::jsonb,
    result          JSONB,
    status          VARCHAR(16) NOT NULL DEFAULT 'queued',
    attempts        SMALLINT NOT NULL DEFAULT 0,
    available_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    locked_by       VARCHAR(128),
    locked_at       TIMESTAMPTZ,
    created_by      BIGINT REFERENCES auth.account(account_id) ON DELETE SET NULL,
    permission_code VARCHAR(100) NOT NULL,
    last_error      VARCHAR(2000),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    started_at      TIMESTAMPTZ,
    finished_at     TIMESTAMPTZ,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_background_job_status
        CHECK (status IN ('queued', 'running', 'succeeded', 'dead')),
    CONSTRAINT ck_background_job_attempts CHECK (attempts BETWEEN 0 AND 3),
    CONSTRAINT ck_background_job_payload CHECK (jsonb_typeof(payload) = 'object'),
    CONSTRAINT ck_background_job_result
        CHECK (result IS NULL OR jsonb_typeof(result) = 'object')
);

CREATE INDEX IF NOT EXISTS ix_background_job_available
    ON audit.background_job (available_at, job_id)
    WHERE status = 'queued';

CREATE INDEX IF NOT EXISTS ix_background_job_creator
    ON audit.background_job (created_by, created_at DESC);
