ALTER TABLE ods.import_batch
    ADD COLUMN IF NOT EXISTS file_sha256 CHAR(64),
    ADD COLUMN IF NOT EXISTS file_size INTEGER,
    ADD COLUMN IF NOT EXISTS input_row_count INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS valid_row_count INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS invalid_row_count INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS skipped_order_count INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS gross_amount NUMERIC(14,2) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS mapping_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    ADD COLUMN IF NOT EXISTS confirmed_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS created_by BIGINT REFERENCES auth.account(account_id);

ALTER TABLE ods.import_batch
    ADD CONSTRAINT ck_import_batch_file_size_nonnegative
        CHECK (file_size IS NULL OR file_size >= 0),
    ADD CONSTRAINT ck_import_batch_row_counts_nonnegative
        CHECK (
            input_row_count >= 0
            AND valid_row_count >= 0
            AND invalid_row_count >= 0
            AND skipped_order_count >= 0
        );

CREATE TABLE IF NOT EXISTS ods.import_stage_row (
    stage_row_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id BIGINT NOT NULL REFERENCES ods.import_batch(batch_id) ON DELETE CASCADE,
    row_number INTEGER NOT NULL CHECK (row_number > 1),
    payload JSONB NOT NULL,
    is_valid BOOLEAN NOT NULL DEFAULT FALSE,
    UNIQUE (batch_id, row_number)
);

CREATE TABLE IF NOT EXISTS ods.import_row_issue (
    issue_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id BIGINT NOT NULL REFERENCES ods.import_batch(batch_id) ON DELETE CASCADE,
    row_number INTEGER NOT NULL CHECK (row_number > 0),
    field_name VARCHAR(64),
    raw_value TEXT,
    issue_code VARCHAR(64) NOT NULL,
    message TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_import_batch_sha
    ON ods.import_batch(file_sha256, created_at DESC)
    WHERE file_sha256 IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_import_stage_batch_valid
    ON ods.import_stage_row(batch_id, is_valid, row_number);

CREATE INDEX IF NOT EXISTS idx_import_issue_batch_row
    ON ods.import_row_issue(batch_id, row_number, issue_id);
