[CmdletBinding()]
param([string]$DatabaseUrl,[string]$EnvFile,[string]$PgBinDir,[string]$BackupDir,[int]$RetentionDays)
$ErrorActionPreference='Stop'
if($EnvFile -and (Test-Path $EnvFile)){Get-Content $EnvFile|%{if($_ -match '^([^#=]+)=(.*)$'){[Environment]::SetEnvironmentVariable($Matches[1],$Matches[2])}}}
if(!$DatabaseUrl){$DatabaseUrl=$env:DATABASE_URL}; if(!$DatabaseUrl -and $env:DB_HOST -and $env:DB_NAME -and $env:DB_USER){$port=if($env:DB_PORT){$env:DB_PORT}else{5432};$DatabaseUrl="postgresql://$([Uri]::EscapeDataString($env:DB_USER)):$([Uri]::EscapeDataString($env:DB_PASSWORD))@$($env:DB_HOST):$port/$($env:DB_NAME)"}; if(!$DatabaseUrl){throw 'DatabaseUrl is required'}; if(!$PgBinDir){$PgBinDir=$env:PG_BIN_DIR}; if(!$BackupDir){$BackupDir=$env:BACKUP_DIR}; if(!$RetentionDays){$RetentionDays=[int]$env:BACKUP_RETENTION_DAYS}; if(!$RetentionDays){$RetentionDays=30}
if(!$PgBinDir -or !(Test-Path $PgBinDir)){throw 'PG_BIN_DIR must point to an existing directory'}; $dump=Join-Path $PgBinDir 'pg_dump.exe'; if(!(Test-Path $dump)){throw 'pg_dump not found'}
$u=[Uri]$DatabaseUrl; $sep=$u.UserInfo.IndexOf(':'); if($sep -lt 0){throw 'DatabaseUrl userinfo must include password'}; $user=[Uri]::UnescapeDataString($u.UserInfo.Substring(0,$sep)); $password=[Uri]::UnescapeDataString($u.UserInfo.Substring($sep+1)); $old=$env:PGPASSWORD; $env:PGHOST=$u.Host;$env:PGPORT=($(if($u.Port -gt 0){$u.Port}else{5432}));$env:PGUSER=$user;$env:PGDATABASE=$u.AbsolutePath.Trim('/');$env:PGPASSWORD=$password; New-Item -ItemType Directory -Force -Path $BackupDir|Out-Null
$name=($env:PGDATABASE -replace '[^A-Za-z0-9_.-]','_');$final=Join-Path $BackupDir "backup-$name-$(Get-Date -Format yyyyMMddHHmmss).dump";$partial="$final.partial"
try{&$dump --format=custom --file $partial; if($LASTEXITCODE){throw 'pg_dump failed'};Move-Item $partial $final -Force;$h=(Get-FileHash $final -Algorithm SHA256).Hash;Set-Content "$final.sha256" "$h  $(Split-Path $final -Leaf)" -NoNewline;Get-ChildItem $BackupDir -File -Filter "backup-$name-*.dump"|? LastWriteTime -lt (Get-Date).AddDays(-$RetentionDays)|%{Remove-Item $_.FullName -Force;Remove-Item "$($_.FullName).sha256" -Force -ErrorAction SilentlyContinue}}catch{Remove-Item $partial -Force -ErrorAction SilentlyContinue;throw}finally{$env:PGPASSWORD=$old}
